name: All Checks

on: [push, pull_request]

jobs:
  gen-ral:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install virtualenv
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Python dependencies
        run: pip install -U -r requirements.txt
      - name: Generate RAL
        run: make ci
      - name: Ensure RAL is consistent with checked-in code
        run: git update-index --refresh && git diff-index --quiet HEAD
      - name: Check format for RAL
        run: cargo fmt --all -- --check

  build-ral-core:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build imxrt-ral for core features
      run: cargo build --verbose
    - name: Test imxrt-ral for core features
      run: cargo test --verbose --tests --lib

  build-ral:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature:
          # Individual chips
          - "imxrt1011"
          - "imxrt1015"
          - "imxrt1021"
          - "imxrt1051"
          - "imxrt1052"
          - "imxrt1061"
          - "imxrt1062"
          - "imxrt1064"
          # Chip + other features
          #
          # Only checking this once, assuming that code gen
          # is consistent across all chips.
          - "imxrt1062,rt"
          - "imxrt1062,rtic"
          - "imxrt1062,rt,rtic"
    steps:
    - uses: actions/checkout@v2
    - name: Build for (${{ matrix.feature }}) RAL
      run: cargo build --verbose --features ${{ matrix.feature }}
    - name: Run tests for (${{ matrix.feature }}) RAL
      run: cargo test --verbose --features ${{ matrix.feature }}

  examples-teensy4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv7em-none-eabihf
          override: true
          profile: minimal
      - name: Build examples/teensy4
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path examples/teensy4/Cargo.toml --target thumbv7em-none-eabihf
